// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'feed_object.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FeedObject _$FeedObjectFromJson(Map<String, dynamic> json) => FeedObject(
      aangebodenSindsTekst: json['AangebodenSindsTekst'] as String?,
      aanmeldDatum: json['AanmeldDatum'] as String?,
      aantalBeschikbaar: json['AantalBeschikbaar'],
      aantalKamers: json['AantalKamers'] as int?,
      aantalKavels: json['AantalKavels'],
      aanvaarding: json['Aanvaarding'] as String?,
      adres: json['Adres'] as String?,
      afstand: json['Afstand'] as int?,
      bronCode: json['BronCode'] as String?,
      childrenObjects: json['ChildrenObjects'],
      datumAanvaarding: json['DatumAanvaarding'],
      datumOndertekeningAkte: json['DatumOndertekeningAkte'],
      foto: json['Foto'] as String?,
      fotoLarge: json['FotoLarge'] as String?,
      fotoLargest: json['FotoLargest'] as String?,
      fotoMedium: json['FotoMedium'] as String?,
      fotoSecure: json['FotoSecure'] as String?,
      gewijzigdDatum: json['GewijzigdDatum'],
      globalId: json['GlobalId'] as int?,
      groupByObjectType: json['GroupByObjectType'] as String?,
      heeft360GradenFoto: json['Heeft360GradenFoto'] as bool?,
      heeftBrochure: json['HeeftBrochure'] as bool?,
      heeftOpenhuizenTopper: json['HeeftOpenhuizenTopper'] as bool?,
      heeftOverbruggingsgrarantie: json['HeeftOverbruggingsgrarantie'] as bool?,
      heeftPlattegrond: json['HeeftPlattegrond'] as bool?,
      heeftTophuis: json['HeeftTophuis'] as bool?,
      heeftVeiling: json['HeeftVeiling'] as bool?,
      heeftVideo: json['HeeftVideo'] as bool?,
      huurPrijsTot: json['HuurPrijsTot'],
      huurprijs: json['Huurprijs'],
      huurprijsFormaat: json['HuurprijsFormaat'],
      id: json['Id'] as String?,
      inUnitsVanaf: json['InUnitsVanaf'],
      indProjectObjectType: json['IndProjectObjectType'] as bool?,
      indTransactieMakelaarTonen: json['IndTransactieMakelaarTonen'],
      isSearchable: json['IsSearchable'] as bool?,
      isVerhuurd: json['IsVerhuurd'] as bool?,
      isVerkocht: json['IsVerkocht'] as bool?,
      isVerkochtOfVerhuurd: json['IsVerkochtOfVerhuurd'] as bool?,
      koopprijs: json['Koopprijs'] as int?,
      koopprijsFormaat: json['KoopprijsFormaat'] as String?,
      koopprijsTot: json['KoopprijsTot'] as int?,
      land: json['Land'] as String?,
      makelaarId: json['MakelaarId'] as int?,
      makelaarNaam: json['MakelaarNaam'] as String?,
      postcode: json['Postcode'] as String?,
      volledigeOmschrijving: json['VolledigeOmschrijving'] as String?,
    );

Map<String, dynamic> _$FeedObjectToJson(FeedObject instance) =>
    <String, dynamic>{
      'AangebodenSindsTekst': instance.aangebodenSindsTekst,
      'AanmeldDatum': instance.aanmeldDatum,
      'AantalBeschikbaar': instance.aantalBeschikbaar,
      'AantalKamers': instance.aantalKamers,
      'AantalKavels': instance.aantalKavels,
      'Aanvaarding': instance.aanvaarding,
      'Adres': instance.adres,
      'Afstand': instance.afstand,
      'BronCode': instance.bronCode,
      'ChildrenObjects': instance.childrenObjects,
      'DatumAanvaarding': instance.datumAanvaarding,
      'DatumOndertekeningAkte': instance.datumOndertekeningAkte,
      'Foto': instance.foto,
      'FotoLarge': instance.fotoLarge,
      'FotoLargest': instance.fotoLargest,
      'FotoMedium': instance.fotoMedium,
      'FotoSecure': instance.fotoSecure,
      'GewijzigdDatum': instance.gewijzigdDatum,
      'GlobalId': instance.globalId,
      'GroupByObjectType': instance.groupByObjectType,
      'Heeft360GradenFoto': instance.heeft360GradenFoto,
      'HeeftBrochure': instance.heeftBrochure,
      'HeeftOpenhuizenTopper': instance.heeftOpenhuizenTopper,
      'HeeftOverbruggingsgrarantie': instance.heeftOverbruggingsgrarantie,
      'HeeftPlattegrond': instance.heeftPlattegrond,
      'HeeftTophuis': instance.heeftTophuis,
      'HeeftVeiling': instance.heeftVeiling,
      'HeeftVideo': instance.heeftVideo,
      'HuurPrijsTot': instance.huurPrijsTot,
      'Huurprijs': instance.huurprijs,
      'HuurprijsFormaat': instance.huurprijsFormaat,
      'Id': instance.id,
      'InUnitsVanaf': instance.inUnitsVanaf,
      'IndProjectObjectType': instance.indProjectObjectType,
      'IndTransactieMakelaarTonen': instance.indTransactieMakelaarTonen,
      'IsSearchable': instance.isSearchable,
      'IsVerhuurd': instance.isVerhuurd,
      'IsVerkocht': instance.isVerkocht,
      'IsVerkochtOfVerhuurd': instance.isVerkochtOfVerhuurd,
      'Koopprijs': instance.koopprijs,
      'KoopprijsFormaat': instance.koopprijsFormaat,
      'KoopprijsTot': instance.koopprijsTot,
      'Land': instance.land,
      'MakelaarId': instance.makelaarId,
      'MakelaarNaam': instance.makelaarNaam,
      'Postcode': instance.postcode,
      'VolledigeOmschrijving': instance.volledigeOmschrijving,
    };
