// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'feed_object.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FeedObject _$FeedObjectFromJson(Map<String, dynamic> json) => FeedObject(
      json['AangebodenSindsTekst'] as String?,
      json['AanmeldDatum'] as String?,
      json['AantalBeschikbaar'],
      json['AantalKamers'] as int?,
      json['AantalKavels'],
      json['Aanvaarding'] as String?,
      json['Adres'] as String?,
      json['Afstand'] as int?,
      json['BronCode'] as String?,
      json['ChildrenObjects'],
      json['DatumAanvaarding'],
      json['DatumOndertekeningAkte'],
      json['Foto'] as String?,
      json['FotoLarge'] as String?,
      json['FotoLargest'] as String?,
      json['FotoMedium'] as String?,
      json['FotoSecure'] as String?,
      json['GewijzigdDatum'],
      json['GlobalId'] as int?,
      json['GroupByObjectType'] as String?,
      json['Heeft360GradenFoto'] as bool?,
      json['HeeftBrochure'] as bool?,
      json['HeeftOpenhuizenTopper'] as bool?,
      json['HeeftOverbruggingsgrarantie'] as bool?,
      json['HeeftPlattegrond'] as bool?,
      json['HeeftTophuis'] as bool?,
      json['HeeftVeiling'] as bool?,
      json['HeeftVideo'] as bool?,
      json['HuurPrijsTot'],
      json['Huurprijs'],
      json['HuurprijsFormaat'],
      json['Id'] as String?,
      json['InUnitsVanaf'],
      json['IndProjectObjectType'] as bool?,
      json['IndTransactieMakelaarTonen'],
      json['IsSearchable'] as bool?,
      json['IsVerhuurd'] as bool?,
      json['IsVerkocht'] as bool?,
      json['IsVerkochtOfVerhuurd'] as bool?,
      json['Koopprijs'] as int?,
      json['KoopprijsFormaat'] as String?,
      json['KoopprijsTot'] as int?,
      json['Land'] as String?,
      json['MakelaarId'] as int?,
      json['MakelaarNaam'] as String?,
      json['Postcode'] as String?,
      json['VolledigeOmschrijving'] as String?,
      (json['Media'] as List<dynamic>?)
              ?.map((e) => Media.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
    );

Map<String, dynamic> _$FeedObjectToJson(FeedObject instance) =>
    <String, dynamic>{
      'AangebodenSindsTekst': instance.aangebodenSindsTekst,
      'AanmeldDatum': instance.aanmeldDatum,
      'AantalBeschikbaar': instance.aantalBeschikbaar,
      'AantalKamers': instance.aantalKamers,
      'AantalKavels': instance.aantalKavels,
      'Aanvaarding': instance.aanvaarding,
      'Adres': instance.adres,
      'Afstand': instance.afstand,
      'BronCode': instance.bronCode,
      'ChildrenObjects': instance.childrenObjects,
      'DatumAanvaarding': instance.datumAanvaarding,
      'DatumOndertekeningAkte': instance.datumOndertekeningAkte,
      'Foto': instance.foto,
      'FotoLarge': instance.fotoLarge,
      'FotoLargest': instance.fotoLargest,
      'FotoMedium': instance.fotoMedium,
      'FotoSecure': instance.fotoSecure,
      'GewijzigdDatum': instance.gewijzigdDatum,
      'GlobalId': instance.globalId,
      'GroupByObjectType': instance.groupByObjectType,
      'Heeft360GradenFoto': instance.heeft360GradenFoto,
      'HeeftBrochure': instance.heeftBrochure,
      'HeeftOpenhuizenTopper': instance.heeftOpenhuizenTopper,
      'HeeftOverbruggingsgrarantie': instance.heeftOverbruggingsgrarantie,
      'HeeftPlattegrond': instance.heeftPlattegrond,
      'HeeftTophuis': instance.heeftTophuis,
      'HeeftVeiling': instance.heeftVeiling,
      'HeeftVideo': instance.heeftVideo,
      'HuurPrijsTot': instance.huurPrijsTot,
      'Huurprijs': instance.huurprijs,
      'HuurprijsFormaat': instance.huurprijsFormaat,
      'Id': instance.id,
      'InUnitsVanaf': instance.inUnitsVanaf,
      'IndProjectObjectType': instance.indProjectObjectType,
      'IndTransactieMakelaarTonen': instance.indTransactieMakelaarTonen,
      'IsSearchable': instance.isSearchable,
      'IsVerhuurd': instance.isVerhuurd,
      'IsVerkocht': instance.isVerkocht,
      'IsVerkochtOfVerhuurd': instance.isVerkochtOfVerhuurd,
      'Koopprijs': instance.koopprijs,
      'KoopprijsFormaat': instance.koopprijsFormaat,
      'KoopprijsTot': instance.koopprijsTot,
      'Land': instance.land,
      'MakelaarId': instance.makelaarId,
      'MakelaarNaam': instance.makelaarNaam,
      'Postcode': instance.postcode,
      'VolledigeOmschrijving': instance.volledigeOmschrijving,
      'Media': instance.media.map((e) => e.toJson()).toList(),
    };
